version: "3.9" 
services:
  db:
    image: mongo
    container_name: dbmongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - C:\Users\cocac\Documents\GitHub\SO1_Practica1_201908335\DBVolumenes:/data/db
    networks:
      - practica1_201908335

  backend:
    image: cocacore7/backend_p1_201908335
    container_name: backend_p1_201908335
    environment:
      MONGO_HOST: db
    ports:
    - "3000:3000"
    restart: always
    depends_on:
    - db
    networks:
    - practica1_201908335

  frontend:
    image: cocacore7/frontend_p1_201908335
    container_name: frontend_p1_201908335
    ports:
    - "4200:4200"
    restart: always
    depends_on:
    - backend
    networks:
    - practica1_201908335
  
volumes:
  mongodata:

networks:
  practica1_201908335:
    name: "practica1_201908335"
    driver: bridge